export const BACKEND_URL  = import.meta.env.VITE_BACKEND_URL
export const STRIPE_MONTHLY_BASIC_PLAN_LINK  = import.meta.env.VITE_STRIPE_MONTHLY_BASIC_PLAN_LINK
export const STRIPE_MONTHLY_PERMIUM_PLAN_LINK  = import.meta.env.VITE_STRIPE_MONTHLY_PERMIUM_PLAN_LINK
